2024-05-30 14:29:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Значение слишком длинное для поля """BODY"" VARCHAR(255)": "'2024-05-30 14:29:37.047 DEBUG 3552 --- [io-62600-exec-3] o.s.web.servlet.DispatcherServlet : Completed 200 OK 2024-05-30 14:29:... (917)"
Value too long for column """BODY"" VARCHAR(255)": "'2024-05-30 14:29:37.047 DEBUG 3552 --- [io-62600-exec-3] o.s.web.servlet.DispatcherServlet : Completed 200 OK 2024-05-30 14:29:... (917)"; SQL statement:
insert into message (created_date, modified_date, body, date, file_info_id, image_file, receiver_username, sender_presentation, sender_username, text_message, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
2024-05-30 14:30:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Значение слишком длинное для поля """BODY"" VARCHAR(255)": "'hello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello he... (306)"
Value too long for column """BODY"" VARCHAR(255)": "'hello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello he... (306)"; SQL statement:
insert into message (created_date, modified_date, body, date, file_info_id, image_file, receiver_username, sender_presentation, sender_username, text_message, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
2024-05-30 14:30:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Значение слишком длинное для поля """BODY"" VARCHAR(255)": "'hello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello he... (306)"
Value too long for column """BODY"" VARCHAR(255)": "'hello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello hello hellohello he... (306)"; SQL statement:
insert into message (created_date, modified_date, body, date, file_info_id, image_file, receiver_username, sender_presentation, sender_username, text_message, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
2024-05-30 14:30:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Значение слишком длинное для поля """BODY"" VARCHAR(255)": "'hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello h... (263)"
Value too long for column """BODY"" VARCHAR(255)": "'hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello h... (263)"; SQL statement:
insert into message (created_date, modified_date, body, date, file_info_id, image_file, receiver_username, sender_presentation, sender_username, text_message, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
2024-05-30 17:05:42 jdbc[65]: null
org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 18 more
